[package]

name    = "nalgebra"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ] # FIXME: add the contributors.

[[lib]]

name       = "nalgebra"
crate_type = [ "dylib", "staticlib" ]
path       = "src/lib.rs"
