[package]
name = "nalgebra-sparse"
version = "0.1.0"
authors = [ "Andreas Longva", "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[features]
proptest-support = ["proptest", "nalgebra/proptest"]
compare = [ "matrixcompare-core" ]

# Enable to enable running some tests that take a lot of time to run
slow-tests = []

[dependencies]
nalgebra = { version="0.23", path = "../" }
num-traits = { version = "0.2", default-features = false }
proptest = { version = "0.10", optional = true }
matrixcompare-core = { version = "0.1.0", optional = true }

[dev-dependencies]
itertools = "0.9"
matrixcompare = { version = "0.2.0", features = [ "proptest-support" ] }
nalgebra = { version="0.23", path = "../", features = ["compare"] }

[package.metadata.docs.rs]
# Enable certain features when building docs for docs.rs
features = [ "proptest-support", "compare" ]